/**
 * Compiles content/agent-kb/*.md into lib/agent/kb.generated.ts so the KB
 * can be inlined into the system prompt at runtime (Workers have no fs).
 * Runs via `npm run kb` (Node 24 native type stripping).
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const kbDir = join(import.meta.dirname, "..", "content", "agent-kb");
const outFile = join(import.meta.dirname, "..", "lib", "agent", "kb.generated.ts");

const files = readdirSync(kbDir)
  .filter((name) => name.endsWith(".md"))
  .sort();

if (files.length === 0) {
  throw new Error(`No knowledge base files found in ${kbDir}`);
}

const kb = files.map((name) => readFileSync(join(kbDir, name), "utf8").trim()).join("\n\n---\n\n");

const banner = `// GENERATED by scripts/build-kb.ts from content/agent-kb/*.md — do not edit.\n// Source files: ${files.join(", ")}\n`;

writeFileSync(outFile, `${banner}export const knowledgeBase = ${JSON.stringify(kb)};\n`);

console.log(`kb.generated.ts written from ${files.length} files (${kb.length} chars)`);
